type
  ImGuiLayoutType* {.pure.} = enum
    Horizontal,
    Vertical,

  ImGuiLogType* {.pure.} = enum
    None,
    TTY,
    File,
    Buffer,
    Clipboard,

  ImGuiAxis* {.pure.} = enum
    None = -1,
    X,
    Y,

  ImGuiPlotType* {.pure.} = enum
    Lines,
    Histogram,

  ImGuiInputSource* {.pure.} = enum
    None,
    Mouse,
    Keyboard,
    Gamepad,
    Nav,
    Clipboard,

  ImGuiInputReadMode* {.pure.} = enum
    Down,
    Pressed,
    Released,
    Repeat,
    RepeatSlow,
    RepeatFast,

  ImGuiNavForward* {.pure.} = enum
    None,
    ForwardQueued,
    ForwardActive,

  ImGuiNavLayer* {.pure.} = enum
    Main,
    Menu,

  ImGuiPopupPositionPolicy* {.pure.} = enum
    Default,
    ComboBox,
    Tooltip,

  ImGuiContextHookType* {.pure.} = enum
    NewFramePre,
    NewFramePost,
    EndFramePre,
    EndFramePost,
    RenderPre,
    RenderPost,
    Shutdown,
    PendingRemoval,

  ImGuiTableBgTarget* {.pure.} = enum
    None,
    RowBg0,
    RowBg1,
    CellBg,

  ImGuiDataType* {.pure.} = enum
    S8,
    U8,
    S16,
    U16,
    S32,
    U32,
    S64,
    U64,
    Float,
    Double,

  ImGuiDataTypePrivate* {.pure.} = enum
    String = ImGuiDataType.Double.int + 2,
    Pointer,
    ID,

  ImGuiDir* {.pure.} = enum
    None = -1,
    Left,
    Right,
    Up,
    Down,

  ImGuiSortDirection* {.pure.} = enum
    None,
    Ascending,
    Descending,

  ImGuiKey* {.pure.} = enum
    Tab,
    LeftArrow,
    RightArrow,
    UpArrow,
    DownArrow,
    PageUp,
    PageDown,
    Home,
    End,
    Insert,
    Delete,
    Backspace,
    Space,
    Enter,
    Escape,
    KeyPadEnter,
    A,
    C,
    V,
    X,
    Y,
    Z,

  ImGuiNavInput* {.pure.} = enum
    Activate,
    Cancel,
    Input,
    Menu,
    DpadLeft,
    DpadRight,
    DpadUp,
    DpadDown,
    LStickLeft,
    LStickRight,
    LStickUp,
    LStickDown,
    FocusPrev,
    FocusNext,
    TweakSlow,
    TweakFast,
    KeyMenu,
    KeyLeft,
    KeyRight,
    KeyUp,
    KeyDown,

  ImGuiCol* {.pure.} = enum
    Text,
    TextDisabled,
    WindowBg,
    ChildBg,
    PopupBg,
    Border,
    BorderShadow,
    FrameBg,
    FrameBgHovered,
    FrameBgActive,
    TitleBg,
    TitleBgActive,
    TitleBgCollapsed,
    MenuBarBg,
    ScrollbarBg,
    ScrollbarGrab,
    ScrollbarGrabHovered,
    ScrollbarGrabActive,
    CheckMark,
    SliderGrab,
    SliderGrabActive,
    Button,
    ButtonHovered,
    ButtonActive,
    Header,
    HeaderHovered,
    HeaderActive,
    Separator,
    SeparatorHovered,
    SeparatorActive,
    ResizeGrip,
    ResizeGripHovered,
    ResizeGripActive,
    Tab,
    TabHovered,
    TabActive,
    TabUnfocused,
    TabUnfocusedActive,
    PlotLines,
    PlotLinesHovered,
    PlotHistogram,
    PlotHistogramHovered,
    TableHeaderBg,
    TableBorderStrong,
    TableBorderLight,
    TableRowBg,
    TableRowBgAlt,
    TextSelectedBg,
    DragDropTarget,
    NavHighlight,
    NavWindowingHighlight,
    NavWindowingDimBg,
    ModalWindowDimBg,

  ImGuiStyleVar* {.pure.} = enum
    Alpha,
    WindowPadding,
    WindowRounding,
    WindowBorderSize,
    WindowMinSize,
    WindowTitleAlign,
    ChildRounding,
    ChildBorderSize,
    PopupRounding,
    PopupBorderSize,
    FramePadding,
    FrameRounding,
    FrameBorderSize,
    ItemSpacing,
    ItemInnerSpacing,
    IndentSpacing,
    CellPadding,
    ScrollbarSize,
    ScrollbarRounding,
    GrabMinSize,
    GrabRounding,
    TabRounding,
    ButtonTextAlign,
    SelectableTextAlign,

  ImGuiMouseButton* {.pure.} = enum
    Left,
    Right,
    Middle,
    X1,
    X2,

  ImGuiMouseCursor* {.pure.} = enum
    None = -1,
    Arrow,
    TextInput,
    ResizeAll,
    ResizeNS,
    ResizeEW,
    ResizeNESW,
    ResizeNWSE,
    Hand,
    NotAllowed,